export {default as Blog} from "./blog/Blog"
export {default as Features} from "./features/Features"
export {default as Footer} from "./footer/Footer"
export {default as Header} from "./header/Header"
export {default as Possibility} from "./possibility/Possiblity"
export {default as WhatGpt3} from "./whatGPt3/WhatGPT3"